# Generated by Django 5.2.1 on 2025-08-08 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='jefe_asignado',
            field=models.OneToOneField(blank=True, help_text='Jefe de local al cual se le asigna la sucursal', null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario'),
        ),
    ]
